
    SELECT 
    e.PRODUCT_ELEMENT_CODE AS SUB_COVERAGE_CODE, 
    pe.PRODUCT_ELEMENT_CODE AS COVERAGE_CODE, 
    UPPER(case 
            when e.PRODUCT_ELEMENT_NAME = 'PRACTICE-MODE' 
            then cast('PRACTICE MODE' as nvarchar2(200))
            else e.PRODUCT_ELEMENT_NAME
            end) AS SUB_COVERAGE_NAME,
    -- UPPER(e.PRODUCT_ELEMENT_NAME) AS SUB_COVERAGE_NAME,
    UPPER(pe.PRODUCT_ELEMENT_NAME) AS COVERAGE_NAME, 
    e.PRODUCT_ELEMENT_ID || '-' || 'GICORE' AS W_INTEGRATION_KEY
    FROM T_PRD_PRODUCT_ELEMENT e
    LEFT JOIN T_PRD_PRODUCT_ELEM_HIERARCHY h ON e.PRODUCT_ELEMENT_ID = h.PRODUCT_ELEMENT_ID
    LEFT JOIN T_PRD_PRODUCT_ELEMENT pe ON h.PARENT_ELEMENT_ID = pe.PRODUCT_ELEMENT_ID AND pe.ELEMENT_TYPE_ID = -1
    WHERE pe.DEFINITION_SUPER_OBJECT_NAME = 'PolicyCoverage'





